import type { Metadata } from "next";
import "./globals.css";
import "aos/dist/aos.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Saud Abbasi | Full Stack Next.js Developer",
    description:
      "Building high-end websites and web apps for startups, businesses, and founders.",
    url: "https://saud-portfolio.vercel.app",
    siteName: "Saud Abbasi",
    images: [
      {
        url: "/preview.webp",
        width: 1200,
        height: 630,
        alt: "Saud Abbasi Portfolio",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
  card: "summary_large_image",
  title: "Saud Abbasi | Full Stack Next.js Developer",
  description:
    "Building high-end websites and web apps for startups, businesses, and founders.",
  images: ["/preview.webp"],
},
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full w-full antialiased`}>
      <body className="">{children}</body>
    </html>
  );
}
